// purple/src/sandbox/seccomp.rs

use crate::error::Result;
use crate::policy::compiler::CompiledSyscallPolicy;
use libseccomp::{ScmpAction, ScmpFilterContext, ScmpSyscall};
use std::collections::BTreeSet;

/// Applies seccomp filtering based on the compiled syscall policy
pub fn apply_seccomp_filter(policy: &CompiledSyscallPolicy) -> Result<()> {
    log::info!("Applying seccomp syscall filter...");

    // Determine default action based on policy
    let default_action = if policy.default_deny {
        ScmpAction::KillProcess
    } else {
        ScmpAction::Allow
    };

    // Create a new seccomp filter context
    let mut ctx = ScmpFilterContext::new_filter(default_action)?;

    if policy.default_deny {
        log::info!("Seccomp: Setting default action to DENY (kill process)");
        log::info!(
            "Seccomp: Allowing {} syscalls",
            policy.allowed_syscall_numbers.len()
        );

        // Add rules for each allowed syscall
        for syscall_num in &policy.allowed_syscall_numbers {
            let syscall = ScmpSyscall::from(*syscall_num as i32);
            ctx.add_rule(ScmpAction::Allow, syscall)?;
            log::debug!("Seccomp: Allowed syscall {}", syscall_num);
        }
    } else {
        log::info!("Seccomp: Setting default action to ALLOW");
        log::info!(
            "Seccomp: Denying {} syscalls",
            policy.denied_syscall_numbers.len()
        );

        // In allow-by-default mode, explicitly deny specific syscalls
        for syscall_num in &policy.denied_syscall_numbers {
            let syscall = ScmpSyscall::from(*syscall_num as i32);
            ctx.add_rule(ScmpAction::KillProcess, syscall)?;
            log::debug!("Seccomp: Denied syscall {}", syscall_num);
        }
    }

    // Load the filter into the kernel
    ctx.load()?;

    if policy.default_deny {
        log::info!(
            "Syscall filtering policy enforced with {} allowed syscalls",
            policy.allowed_syscall_numbers.len()
        );
    } else {
        log::info!(
            "Syscall filtering policy enforced with {} denied syscalls",
            policy.denied_syscall_numbers.len()
        );
    }

    Ok(())
}

/// Syscall name to number mapping for common syscalls
/// Note: Kept for potential future dynamic syscall resolution
#[allow(dead_code)]
pub fn get_syscall_number(name: &str) -> Option<i64> {
    // This is a partial mapping. In a production system, you might want to
    // use a more comprehensive approach or generate this from system headers.
    match name {
        // File operations
        "read" => Some(0),
        "write" => Some(1),
        "open" => Some(2),
        "close" => Some(3),
        "stat" => Some(4),
        "fstat" => Some(5),
        "lstat" => Some(6),
        "poll" => Some(7),
        "lseek" => Some(8),
        "mmap" => Some(9),
        "mprotect" => Some(10),
        "munmap" => Some(11),
        "brk" => Some(12),
        "rt_sigaction" => Some(13),
        "rt_sigprocmask" => Some(14),
        "rt_sigreturn" => Some(15),
        "ioctl" => Some(16),
        "pread64" => Some(17),
        "pwrite64" => Some(18),
        "readv" => Some(19),
        "writev" => Some(20),
        "access" => Some(21),
        "pipe" => Some(22),
        "select" => Some(23),
        "sched_yield" => Some(24),
        "mremap" => Some(25),
        "msync" => Some(26),
        "mincore" => Some(27),
        "madvise" => Some(28),
        "shmget" => Some(29),
        "shmat" => Some(30),
        "shmctl" => Some(31),
        "dup" => Some(32),
        "dup2" => Some(33),
        "pause" => Some(34),
        "nanosleep" => Some(35),
        "getitimer" => Some(36),
        "alarm" => Some(37),
        "setitimer" => Some(38),
        "getpid" => Some(39),
        "sendfile" => Some(40),
        "socket" => Some(41),
        "connect" => Some(42),
        "accept" => Some(43),
        "sendto" => Some(44),
        "recvfrom" => Some(45),
        "sendmsg" => Some(46),
        "recvmsg" => Some(47),
        "shutdown" => Some(48),
        "bind" => Some(49),
        "listen" => Some(50),
        "getsockname" => Some(51),
        "getpeername" => Some(52),
        "socketpair" => Some(53),
        "setsockopt" => Some(54),
        "getsockopt" => Some(55),
        "clone" => Some(56),
        "fork" => Some(57),
        "vfork" => Some(58),
        "execve" => Some(59),
        "exit" => Some(60),
        "wait4" => Some(61),
        "kill" => Some(62),
        "uname" => Some(63),
        "semget" => Some(64),
        "semop" => Some(65),
        "semctl" => Some(66),
        "shmdt" => Some(67),
        "msgget" => Some(68),
        "msgsnd" => Some(69),
        "msgrcv" => Some(70),
        "msgctl" => Some(71),
        "fcntl" => Some(72),
        "flock" => Some(73),
        "fsync" => Some(74),
        "fdatasync" => Some(75),
        "truncate" => Some(76),
        "ftruncate" => Some(77),
        "getdents" => Some(78),
        "getcwd" => Some(79),
        "chdir" => Some(80),
        "fchdir" => Some(81),
        "rename" => Some(82),
        "mkdir" => Some(83),
        "rmdir" => Some(84),
        "creat" => Some(85),
        "link" => Some(86),
        "unlink" => Some(87),
        "symlink" => Some(88),
        "readlink" => Some(89),
        "chmod" => Some(90),
        "fchmod" => Some(91),
        "chown" => Some(92),
        "fchown" => Some(93),
        "lchown" => Some(94),
        "umask" => Some(95),
        "gettimeofday" => Some(96),
        "getrlimit" => Some(97),
        "getrusage" => Some(98),
        "sysinfo" => Some(99),
        "times" => Some(100),
        "ptrace" => Some(101),
        "getuid" => Some(102),
        "syslog" => Some(103),
        "getgid" => Some(104),
        "setuid" => Some(105),
        "setgid" => Some(106),
        "geteuid" => Some(107),
        "getegid" => Some(108),
        "setpgid" => Some(109),
        "getppid" => Some(110),
        "getpgrp" => Some(111),
        "setsid" => Some(112),
        "setreuid" => Some(113),
        "setregid" => Some(114),
        "getgroups" => Some(115),
        "setgroups" => Some(116),
        "setresuid" => Some(117),
        "getresuid" => Some(118),
        "setresgid" => Some(119),
        "getresgid" => Some(120),
        "getpgid" => Some(121),
        "setfsuid" => Some(122),
        "setfsgid" => Some(123),
        "getsid" => Some(124),
        "capget" => Some(125),
        "capset" => Some(126),
        "rt_sigpending" => Some(127),
        "rt_sigtimedwait" => Some(128),
        "rt_sigqueueinfo" => Some(129),
        "rt_sigsuspend" => Some(130),
        "sigaltstack" => Some(131),
        "utime" => Some(132),
        "mknod" => Some(133),
        "uselib" => Some(134),
        "personality" => Some(135),
        "ustat" => Some(136),
        "statfs" => Some(137),
        "fstatfs" => Some(138),
        "sysfs" => Some(139),
        "getpriority" => Some(140),
        "setpriority" => Some(141),
        "sched_setparam" => Some(142),
        "sched_getparam" => Some(143),
        "sched_setscheduler" => Some(144),
        "sched_getscheduler" => Some(145),
        "sched_get_priority_max" => Some(146),
        "sched_get_priority_min" => Some(147),
        "sched_rr_get_interval" => Some(148),
        "mlock" => Some(149),
        "munlock" => Some(150),
        "mlockall" => Some(151),
        "munlockall" => Some(152),
        "vhangup" => Some(153),
        "modify_ldt" => Some(154),
        "pivot_root" => Some(155),
        "_sysctl" => Some(156),
        "prctl" => Some(157),
        "arch_prctl" => Some(158),
        "adjtimex" => Some(159),
        "setrlimit" => Some(160),
        "chroot" => Some(161),
        "sync" => Some(162),
        "acct" => Some(163),
        "settimeofday" => Some(164),
        "mount" => Some(165),
        "umount2" => Some(166),
        "unmount" => Some(166), // Alias for umount2
        "swapon" => Some(167),
        "swapoff" => Some(168),
        "reboot" => Some(169),
        "sethostname" => Some(170),
        "setdomainname" => Some(171),
        "iopl" => Some(172),
        "ioperm" => Some(173),
        "create_module" => Some(174),
        "init_module" => Some(175),
        "delete_module" => Some(176),
        "get_kernel_syms" => Some(177),
        "query_module" => Some(178),
        "quotactl" => Some(179),
        "nfsservctl" => Some(180),
        "getpmsg" => Some(181),
        "putpmsg" => Some(182),
        "afs_syscall" => Some(183),
        "tuxcall" => Some(184),
        "security" => Some(185),
        "gettid" => Some(186),
        "readahead" => Some(187),
        "setxattr" => Some(188),
        "lsetxattr" => Some(189),
        "fsetxattr" => Some(190),
        "getxattr" => Some(191),
        "lgetxattr" => Some(192),
        "fgetxattr" => Some(193),
        "listxattr" => Some(194),
        "llistxattr" => Some(195),
        "flistxattr" => Some(196),
        "removexattr" => Some(197),
        "lremovexattr" => Some(198),
        "fremovexattr" => Some(199),
        "tkill" => Some(200),
        "time" => Some(201),
        "futex" => Some(202),
        "sched_setaffinity" => Some(203),
        "sched_getaffinity" => Some(204),
        "set_thread_area" => Some(205),
        "io_setup" => Some(206),
        "io_destroy" => Some(207),
        "io_getevents" => Some(208),
        "io_submit" => Some(209),
        "io_cancel" => Some(210),
        "get_thread_area" => Some(211),
        "lookup_dcookie" => Some(212),
        "epoll_create" => Some(213),
        "epoll_ctl_old" => Some(214),
        "epoll_wait_old" => Some(215),
        "remap_file_pages" => Some(216),
        "getdents64" => Some(217),
        "set_tid_address" => Some(218),
        "restart_syscall" => Some(219),
        "semtimedop" => Some(220),
        "fadvise64" => Some(221),
        "timer_create" => Some(222),
        "timer_settime" => Some(223),
        "timer_gettime" => Some(224),
        "timer_getoverrun" => Some(225),
        "timer_delete" => Some(226),
        "clock_settime" => Some(227),
        "clock_gettime" => Some(228),
        "clock_getres" => Some(229),
        "clock_nanosleep" => Some(230),
        "exit_group" => Some(231),
        "epoll_wait" => Some(232),
        "epoll_ctl" => Some(233),
        "tgkill" => Some(234),
        "utimes" => Some(235),
        "vserver" => Some(236),
        "mbind" => Some(237),
        "set_mempolicy" => Some(238),
        "get_mempolicy" => Some(239),
        "mq_open" => Some(240),
        "mq_unlink" => Some(241),
        "mq_timedsend" => Some(242),
        "mq_timedreceive" => Some(243),
        "mq_notify" => Some(244),
        "mq_getsetattr" => Some(245),
        "kexec_load" => Some(246),
        "waitid" => Some(247),
        "add_key" => Some(248),
        "request_key" => Some(249),
        "keyctl" => Some(250),
        "ioprio_set" => Some(251),
        "ioprio_get" => Some(252),
        "inotify_init" => Some(253),
        "inotify_add_watch" => Some(254),
        "inotify_rm_watch" => Some(255),
        "migrate_pages" => Some(256),
        "openat" => Some(257),
        "mkdirat" => Some(258),
        "mknodat" => Some(259),
        "fchownat" => Some(260),
        "futimesat" => Some(261),
        "newfstatat" => Some(262),
        "unlinkat" => Some(263),
        "renameat" => Some(264),
        "linkat" => Some(265),
        "symlinkat" => Some(266),
        "readlinkat" => Some(267),
        "fchmodat" => Some(268),
        "faccessat" => Some(269),
        "pselect6" => Some(270),
        "ppoll" => Some(271),
        "unshare" => Some(272),
        "set_robust_list" => Some(273),
        "get_robust_list" => Some(274),
        "splice" => Some(275),
        "tee" => Some(276),
        "sync_file_range" => Some(277),
        "vmsplice" => Some(278),
        "move_pages" => Some(279),
        "utimensat" => Some(280),
        "epoll_pwait" => Some(281),
        "signalfd" => Some(282),
        "timerfd_create" => Some(283),
        "eventfd" => Some(284),
        "fallocate" => Some(285),
        "timerfd_settime" => Some(286),
        "timerfd_gettime" => Some(287),
        "accept4" => Some(288),
        "signalfd4" => Some(289),
        "eventfd2" => Some(290),
        "epoll_create1" => Some(291),
        "dup3" => Some(292),
        "pipe2" => Some(293),
        "inotify_init1" => Some(294),
        "preadv" => Some(295),
        "pwritev" => Some(296),
        "rt_tgsigqueueinfo" => Some(297),
        "perf_event_open" => Some(298),
        "recvmmsg" => Some(299),
        "fanotify_init" => Some(300),
        "fanotify_mark" => Some(301),
        "prlimit64" => Some(302),
        "name_to_handle_at" => Some(303),
        "open_by_handle_at" => Some(304),
        "clock_adjtime" => Some(305),
        "syncfs" => Some(306),
        "sendmmsg" => Some(307),
        "setns" => Some(308),
        "getcpu" => Some(309),
        "process_vm_readv" => Some(310),
        "process_vm_writev" => Some(311),
        "kcmp" => Some(312),
        "finit_module" => Some(313),
        "sched_setattr" => Some(314),
        "sched_getattr" => Some(315),
        "renameat2" => Some(316),
        "seccomp" => Some(317),
        "getrandom" => Some(318),
        "memfd_create" => Some(319),
        "kexec_file_load" => Some(320),
        "bpf" => Some(321),
        "execveat" => Some(322),
        "userfaultfd" => Some(323),
        "membarrier" => Some(324),
        "mlock2" => Some(325),
        "copy_file_range" => Some(326),
        "preadv2" => Some(327),
        "pwritev2" => Some(328),
        "pkey_alloc" => Some(329),
        "pkey_free" => Some(330),
        "statx" => Some(332),
        "io_pgetevents" => Some(333),
        "rseq" => Some(334),
        "pidfd_send_signal" => Some(424),
        "io_uring_setup" => Some(425),
        "io_uring_enter" => Some(426),
        "io_uring_register" => Some(427),
        "open_tree" => Some(428),
        "move_mount" => Some(429),
        "fsopen" => Some(430),
        "fsconfig" => Some(431),
        "fsmount" => Some(432),
        "fspick" => Some(433),
        "pidfd_open" => Some(434),
        "clone3" => Some(435),
        "close_range" => Some(436),
        "openat2" => Some(437),
        "pidfd_getfd" => Some(438),
        "faccessat2" => Some(439),
        "process_madvise" => Some(440),
        "epoll_pwait2" => Some(441),
        "mount_setattr" => Some(442),
        "landlock_create_ruleset" => Some(444),
        "landlock_add_rule" => Some(445),
        "landlock_restrict_self" => Some(446),
        "memfd_secret" => Some(447),
        "process_mrelease" => Some(448),
        "futex_waitv" => Some(449),
        "set_mempolicy_home_node" => Some(450),
        _ => None,
    }
}

/// Converts syscall names to numbers for the policy
/// Note: Kept for potential future dynamic syscall resolution
#[allow(dead_code)]
pub fn resolve_syscall_names(names: &[String]) -> BTreeSet<i64> {
    let mut numbers = BTreeSet::new();
    for name in names {
        if let Some(num) = get_syscall_number(name) {
            numbers.insert(num);
        } else {
            log::warn!("Unknown syscall name: {}", name);
        }
    }
    numbers
}
